// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnygtx_GbNU_4KNyzQ6m0G3HLNzjookQ',
    appId: '1:362774021505:web:5edaa6a66def5888c9d480',
    messagingSenderId: '362774021505',
    projectId: 'flutterweather-ae97b',
    authDomain: 'flutterweather-ae97b.firebaseapp.com',
    storageBucket: 'flutterweather-ae97b.firebasestorage.app',
    measurementId: 'G-45EF95W645',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvIItXxoOXkw61Pz-Z1hWX-syMeRp2_sc',
    appId: '1:362774021505:android:44fdc0f1dbf0d6a9c9d480',
    messagingSenderId: '362774021505',
    projectId: 'flutterweather-ae97b',
    storageBucket: 'flutterweather-ae97b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVQKHjpeDzEHT2q9pO5ai9nyycAaQZ1U',
    appId: '1:362774021505:ios:cb3fcf52fb012188c9d480',
    messagingSenderId: '362774021505',
    projectId: 'flutterweather-ae97b',
    storageBucket: 'flutterweather-ae97b.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVQKHjpeDzEHT2q9pO5ai9nyycAaQZ1U',
    appId: '1:362774021505:ios:cb3fcf52fb012188c9d480',
    messagingSenderId: '362774021505',
    projectId: 'flutterweather-ae97b',
    storageBucket: 'flutterweather-ae97b.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgnygtx_GbNU_4KNyzQ6m0G3HLNzjookQ',
    appId: '1:362774021505:web:6b44ea3c3b999a20c9d480',
    messagingSenderId: '362774021505',
    projectId: 'flutterweather-ae97b',
    authDomain: 'flutterweather-ae97b.firebaseapp.com',
    storageBucket: 'flutterweather-ae97b.firebasestorage.app',
    measurementId: 'G-87YTDBWY37',
  );
}
